services:
  - type: web
    name: yadawy-store
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_EXPIRES_IN
        value: 8h
      - key: ADMIN_EMAIL
        value: admin@yadawy.com
      - key: ADMIN_PASSWORD
        value: YadawyAdmin2024!
      - key: NOTIFICATION_EMAIL
        value: yadawy1980@gmail.com
      - key: SMTP_HOST
        value: smtp.gmail.com
      - key: SMTP_PORT
        value: 587
      - key: SMTP_SECURE
        value: false
      - key: SMTP_USER
        value: yadawy1980@gmail.com
      - key: SMTP_PASS
        value: cududnowswvaoppy
      - key: SMTP_FROM
        value: '"Yadawy Store" <yadawy1980@gmail.com>'
